## **Reading csv files with python**

In [ ]:
import csv

with open('../datasets/mpg.csv') as csvfile:
  mpg = list(csv.DictReader(csvfile))

mpg[:3] # The first three dictionaries in our list.

**Summing data in a csv file**

In [3]:
sum(float(d['cty']) for d in mpg)

3945.0

## **Numpy**

The Numpy module is mainly used for working with numerical 
data. It provides us with a powerful object known as an Array.
With Arrays, we can perform mathematical operations on 
multiple values in the Arrays at the same time, and also
perform operations between different Arrays, similar to 
matrix operations. 

In [1]:
import numpy as np
import math 

**Array creation**

In [2]:
a = np.array([1,2,3,4])
print(a.ndim)

1


Two dimensional array

In [3]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.ndim)

2


In [4]:
print(b.shape)
# 2 by 4

(2, 4)


Adding default values to an array

In [7]:
c = np.zeros((2,4))
print(c)
d = np.ones((3,2))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
