## **Reading csv files with python**

In [39]:
import csv

with open('../datasets/mpg.csv') as csvfile:
  mpg = list(csv.DictReader(csvfile))

mpg[:3] # The first three dictionaries in our list.

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

**Summing data in a csv file**

In [40]:
sum(float(d['cty']) for d in mpg)

3945.0

## **Numpy**

The Numpy module is mainly used for working with numerical 
data. It provides us with a powerful object known as an Array.
With Arrays, we can perform mathematical operations on 
multiple values in the Arrays at the same time, and also
perform operations between different Arrays, similar to 
matrix operations. 

In [41]:
import numpy as np
import math 

**Array creation**

In [42]:
a = np.array([1,2,3,4])
print(a.ndim)

1


Two dimensional array

In [43]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.ndim)

2


In [44]:
print(b.shape)
# 2 by 4

(2, 4)


Adding default values to an array

In [45]:
c = np.zeros((2,4))
print(c)
d = np.ones((3,2))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


**Array operations**

In [46]:
e = np.arange(0, 10, 2)
f = np.linspace(0, 10, 5)

print(e)
print(f)
print(e+f)
print(e*f)
print(e**2)
print(e-f)
print(e/f)


[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[ 0.   4.5  9.  13.5 18. ]
[ 0.  5. 20. 45. 80.]
[ 0  4 16 36 64]
[ 0.  -0.5 -1.  -1.5 -2. ]
[nan 0.8 0.8 0.8 0.8]


/tmp/ipykernel_177041/3640568740.py:10: RuntimeWarning: invalid value encountered in divide
  print(e/f)


In [47]:
# Use reshape to change the shape of an array

g = np.array([1,2,3,4])
print(g.reshape(2,2))

[[1 2]
 [3 4]]


In [48]:
g=g*2
print(g)

[2 4 6 8]


## **REGEX**

In [49]:
import re

str = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

print(re.search("Amy", str))

print(re.split("Amy", str))

print(re.findall("Amy", str))


<re.Match object; span=(0, 3), match='Amy'>
['', ' works diligently. ', ' gets good grades. Our student ', ' is succesful.']
['Amy', 'Amy', 'Amy']


### **Patterns and character classes**

#### **Set Operators**

In [50]:
# Set Operator
grades="ACAAAABCBCBAA"
re.findall("[AB]", grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']

In [51]:
re.findall("[A][B-C]", grades)

['AC', 'AB']

In [52]:
# You could use the or operator | to get the same result
re.findall("AB|AC", grades)

['AC', 'AB']

**Caret - ^**

In [53]:
# Check if the 1st character is A
re.findall("^A", grades)

['A']

In [54]:
# Check if the first character is B
re.findall("^B", grades)

[]

In [55]:
# Since it is not B, it will return an empty list

**Dollar Sign - $**

In [56]:
# Check if the last character is A
re.findall("A$", grades)

['A']

In [57]:
# Check if the last character is B
re.findall("B$", grades)

[]

In [58]:
# Since the last character is not B, it will return an empty list

In [59]:
# Return a list excluding A
re.findall("[^A]", grades)

['C', 'B', 'C', 'B', 'C', 'B']

In [60]:
# Return an empty list
re.findall("^[^A]", grades)

[]

#### **Quantifiers**


In [61]:
# Quantifiers are the number of times you want a pattern to be matched in order to match. The most basic
# quantifier is expressed as e{m,n}, where e is the expression or character we are matching, m is the minimum
# number of times you want it to matched, and n is the maximum number of times the item could be matched.

# Let's use these grades as an example. How many times has this student been on a back-to-back A's streak?
re.findall("A{2,10}", grades) # 2 is the min and 10 is the max

['AAAA', 'AA']

In [62]:
# So we see that there were two streaks, one where the student had four A's, and one where they had only two
# A's

# We might try and do this using single values and just repeating the pattern
re.findall("A{1,1}A{1,1}", grades)

['AA', 'AA', 'AA']

In [63]:
# As you can see, this is different than the first example. The first pattern is looking for any combination
# of two A's up to ten A's in a row. So it sees four A's as a single streak. The second pattern is looking for
# two A's back to back, so it sees two A's followed immediately by two more A's. We say that the regex
# processor begins at the start of the string and consumes variables which match patterns as it does.

# It's important to note that the regex quantifier syntax does not allow you to deviate from the {m,n}
# pattern. In particular, if you have an extra space in between the braces you'll get an empty result
re.findall("A{2, 2}",grades)

[]

In [64]:
# One number in braces 
re.findall("A{2}",grades)

['AA', 'AA', 'AA']

In [65]:
# Using this, we could find a decreasing trend in a student's grades
re.findall("A{1,10}B{1,10}C{1,10}",grades)

['AAAABC']

## **Pandas**

Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data. The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

#### **The Series Data Structure in Pandas**

A pandas Series is a one-dimensional array. It holds any data type supported in Python and uses labels to locate each data value for retrieval. These labels form the index, and they can be strings or integers. A Series is the main data structure in the pandas framework for storing one-dimensional data.

The series is one of the core data structures in pandas. You think of it a cross between a list and a dictionary. The items are all stored in an order and there's labels with which you can retrieve them. An easy way to visualize this is two columns of data. The first is the special index, a lot like keys in a dictionary. While the second is your actual data. It's important to note that the data column has a label of its own and can be retrieved using the .name attribute. This is different than with dictionaries and is useful when it comes to merging multiple columns of data. And we'll talk about that later on in the course.

In [66]:
import pandas as pd

students = ['Alice', 'Jack', 'Molly']
pd.Series(students)
# stype is object

0    Alice
1     Jack
2    Molly
dtype: object

In [67]:
numbers = [1, 2, 3]
pd.Series(numbers)
# dtype is int64

0    1
1    2
2    3
dtype: int64

In [68]:
# Adding None to a list of strings
students = ['Alice', 'Jack', None]
pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [69]:
# Above returns dtype as object and None.

# Adding None to a list of numbers
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [70]:
# Above, I get dtype as float64 and NaN. Nan is not None and when we try to do equality test, it's false.
import numpy as np
np.nan == None

False

In [71]:
# So we can't use equality test to see if the value is missing or not. Instead, we need to use special function 
np.isnan(np.nan)

True

In [72]:
# Here, we shall convert a dictionary to a series
students_scores = {'Alice': 'Physics', 'Jack': 'Chemistry', 'Molly': 'English'}
s = pd.Series(students_scores)

In [73]:
# The indices in the series are built from the keys of the dictionary that we provided. We can override this
s.index
# Here, we got the index attribute using .index

Index(['Alice', 'Jack', 'Molly'], dtype='object')

In [75]:
s = pd.Series(students_scores, index=['Bob', 'Jack', 'Paul'])
s
# Here, we were trying to return each of the students and their scores. But since Bob and Paul are not in the series, we get NaN.

Bob           NaN
Jack    Chemistry
Paul          NaN
dtype: object

In [76]:
# You can also separate your index creation from the data by passing in the index as a 
# list explicitly to the series.

s = pd.Series(['Physics', 'Chemistry', 'English'], index=['Alice', 'Jack', 'Molly'])
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [ ]:
# Here, we shall convert a dictionary to a series
students_scores = {'Alice': 'Physics', 'Jack': 'Chemistry', 'Molly': 'English'}
s = pd.Series(students_scores)